project:
  type: website
  output-dir: _site

website:
  title: "ML6 Senior Engineer Challenge"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: clustering_sensors/site/analysis.ipynb
        text: Clustering Analysis
      - href: presentation.qmd
        text: Slides

execute:
  plotly-connected: true

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

jupyter: ml6-clustering
